PREPROCESSING:
  DATASET: FF++
  COMPRESSION: c0
  SPLIT: test
  ROOT: /home/S21_D/research/LAA-Net/data/FF++/FaceForensics++/c0/
  FAKETYPE: [Original]

  IMAGE_SUFFIX: png
  DATA_TYPE: frames
  LABEL: [real]
  facial_lm_pretrained: pretrained/shape_predictor_81_face_landmarks.dat
  N_LANDMARKS: 81
  SAMPLING:
    ACTIVE: False
    NUMBERS: 8
  DEBUG: False
